name: Donetick
slug: donetick
description: Self-hosted Donetick chore/task manager
version: "v0.1.52-ha1"        # your add-on's version; bump when you update
arch: ["amd64","aarch64"]

# Supervisor will build using Dockerfile + build.json


# We BUILD this add-on (no 'image:' key here)
ports:
  "2021/tcp": 2021             # external port on HA host

# Mount HA-managed dirs
map: ["config:rw","data:rw"]

# === UI-configurable options shown in HA ===
options:
  sqlite_path: /data/donetick.db
  jwt_secret: ""
  serve_frontend: true
  realtime_enabled: true
  realtime_max_connections: 64
  realtime_max_connections_per_user: 4
  realtime_event_queue_size: 256          # NEW

schema:
  sqlite_path: str
  jwt_secret: password?
  serve_frontend: bool
  realtime_enabled: bool
  realtime_max_connections: int
  realtime_max_connections_per_user: int
  realtime_event_queue_size: int          # NEW 

startup: services
init: false
webui: "http://[HOST]:[PORT:2021]"