name: Donetick
slug: donetick
description: Self-hosted Donetick chore/task manager
version: "v0.1.52-ha8"        # your add-on's version; bump when you update
arch: ["amd64","aarch64"]

# Build mode (Dockerfile/build.json present)
ports:
  "2021/tcp": 2021

map: ["config:rw","data:rw"]

# ---------- BASIC OPTIONS ----------
options:
  sqlite_path: /data/donetick.db
  jwt_secret: ""                # blank → auto-generate (≥32 chars)
  serve_frontend: true
  realtime_enabled: true

  # ---------- ADVANCED TOGGLE ----------
  advanced: false               # when false, we write safe defaults below

  # ---------- ADVANCED REALTIME (used only if advanced: true) ----------
  realtime_max_connections: 1000
  realtime_max_connections_per_user: 5
  realtime_event_queue_size: 2048
  realtime_heartbeat_interval: 60s
  realtime_connection_timeout: 120s
  realtime_cleanup_interval: 2m
  realtime_stale_threshold: 5m
  realtime_sse_enabled: true
  realtime_enable_compression: true
  realtime_enable_stats: true
  realtime_allowed_origins:
    - "*"                       # list; add domains if you want
  debug_logging: false          # simple ON/OFF switch
  logging_level: info           # used when debug_logging = false
  logging_encoding: console     # console | json
  logging_development: false    # zap "development" mode
  server_cors_allow_origins:
    - "*"
  server_rate_limit: 300
  server_rate_period: 60s
  server_read_timeout: 10s
  server_write_timeout: 10s


schema:
  sqlite_path: str
  jwt_secret: password?
  serve_frontend: bool
  realtime_enabled: bool
  advanced: bool
  realtime_max_connections: int
  realtime_max_connections_per_user: int
  realtime_event_queue_size: int
  realtime_heartbeat_interval: str
  realtime_connection_timeout: str
  realtime_cleanup_interval: str
  realtime_stale_threshold: str
  realtime_sse_enabled: bool
  realtime_enable_compression: bool
  realtime_enable_stats: bool
  realtime_allowed_origins:
    - str
  debug_logging: bool
  logging_level: list(debug|info|warn|error)
  logging_encoding: list(console|json)
  logging_development: bool
  server_cors_allow_origins:
    - str
  server_rate_limit: int
  server_rate_period: str
  server_read_timeout: str
  server_write_timeout: str

startup: services
init: false
webui: "http://[HOST]:[PORT:2021]"